2020-02-17 19:08:52,794 	 [INFO | run_locally.py : line 30] >> Pipeline start
2020-02-17 19:08:52,795 	 [INFO | run_locally.py : line 34] >> No run mode provided. Run mode defaulted to run_bau
2020-02-17 19:08:52,834 	 [INFO | dataimport.py : line 93] >> Connect to mysql db succeed
2020-02-17 19:08:57,353 	 [INFO | dataimport.py : line 134] >> site=90515 | Data (pressure) is loaded
2020-02-17 19:08:57,362 	 [ERROR | dataimport.py : line 139] >> site=03805_PRV | 1265 - 01000 - Data truncated for column 'value' at row 1. Check log
2020-02-17 19:08:57,367 	 [INFO | dataimport.py : line 37] >> site=03805_PRV | utils/configuration_failed_files.csv is generated
2020-02-17 19:08:57,368 	 [INFO | dataimport.py : line 153] >> Disconnect from mysql db succeed
2020-02-17 19:08:57,369 	 [INFO | run_locally.py : line 65] >> Pipeline end
