2020-02-29 19:28:41,449 	 [INFO | run_locally.py : line 30] >> Pipeline start
2020-02-29 19:28:41,450 	 [INFO | run_locally.py : line 45] >> Using this configuration file = utils/adhoc_config.csv
2020-02-29 19:28:41,487 	 [ERROR | run_locally.py : line 65] >> Database dpm-solution1 not found
